### ISSUE TITLE
Simple example with `bind:fen` not working

### ISSUE THREAD

**Issue by jacksonthall22** [gtim/svelte-chess#69]
Maybe I'm using this wrong or in a way that was not intended (I'm newish to Svelte/SvelteKit). In the code below, changing the text in the `input` box is reflected in the paragraph tag below, but it does not update the board state. On the readme docs, it has a "bindable" check next to `fen`, so I expected this to work. Why doesn't the board state change when the value of the text box changes? Is there a better way to update the state with J/TS? Thanks in advance.

```svelte
<script lang="ts">
    import { Chess } from 'svelte-chess';

    let fen = 'rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2';
</script>
    
<section style='width: 50%; margin: 0 auto;'>
    <Chess bind:fen={fen} />
    <!-- <Chess bind:fen /> -->
    <input bind:value={fen}  style='width: 100%;' />
    <p>{fen}</p>
</section>
```

**Comment by gtim** [comment]
Hi! Svelte doesn't distinguish write-bindable and read-bindable very well. `fen` is read-bindable  and updated whenever the game state changes. It's directly writable too, but only when the component is initialised. I'll update the docs to make that clearer. 

To update the fen later, use the `load(fen)` function:

```
<script lang="ts">
    import { Chess } from 'svelte-chess';
    let chess: Chess;

    let fen = 'rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2';
    $: chess?.load( fen );
</script>
    
<section style='width: 50%; margin: 0 auto;'>
    <Chess bind:fen={fen} bind:this={chess} />
    <input bind:value={fen}  style='width: 100%;' />
    <p>{fen}</p>
</section>
```

Or, to also make sure it won't crash as soon as there's an invalid FEN in the text field:

```
<script lang="ts">
    import { Chess } from 'svelte-chess';
    let chess: Chess;

    let fen = 'rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2';
    $: try {
        chess?.load( fen );
    } catch (e) {};
</script>
    
<section style='width: 50%; margin: 0 auto;'>
    <Chess bind:fen={fen} bind:this={chess} />
    <input bind:value={fen}  style='width: 100%;' />
    <p>{fen}</p>
</section>
```

Let me know if this fixed the issue or there's any other problem!

Cheers

**Comment by jacksonthall22** [comment]
This works great, thanks for the prompt response and for your work on these great libraries!
